version: "3"
services:
  mongo-express:
    restart: always
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    restart: always
    image: library/mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "casa-popular"
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - mongo-compose-network

volumes:
  mongodb_data_container:
networks:
  mongo-compose-network:
    driver: bridge